// Per-question explanations for the DSA tracker: a short problem statement, one
// worked example (input → output → why), and a one-line optimal-approach hint.
// Keyed by the question number used in 11-dsa-coding-questions.md.

export type DsaDetail = {
  statement: string;
  input: string;
  output: string;
  why: string;
  approach: string;
};

export const DSA_DETAILS: Record<number, DsaDetail> = {
  // ===== 1. Arrays & Hashing =====
  1: {
    statement: "Return the indices of the two numbers in an array that add up to a given target.",
    input: "nums = [2,7,11,15], target = 9",
    output: "[0,1]",
    why: "nums[0] + nums[1] = 2 + 7 = 9.",
    approach: "Hash map of value→index; check target − num in one pass. O(n).",
  },
  2: {
    statement: "Find the maximum profit from buying on one day and selling on a later day.",
    input: "prices = [7,1,5,3,6,4]",
    output: "5",
    why: "Buy at 1 (day 2), sell at 6 (day 5): profit 5.",
    approach: "Track min price so far and best profit in one pass. O(n).",
  },
  3: {
    statement: "Return true if any value appears at least twice in the array.",
    input: "nums = [1,2,3,1]",
    output: "true",
    why: "The value 1 appears twice.",
    approach: "Insert into a hash set; duplicate if size stops growing. O(n).",
  },
  4: {
    statement: "Return an array where each element is the product of all others, without division.",
    input: "nums = [1,2,3,4]",
    output: "[24,12,8,6]",
    why: "Each slot multiplies every other element (e.g. 2·3·4 = 24).",
    approach: "Prefix products left→right, then suffix products right→left. O(n).",
  },
  5: {
    statement: "Find the contiguous subarray with the largest sum.",
    input: "nums = [-2,1,-3,4,-1,2,1,-5,4]",
    output: "6",
    why: "Subarray [4,-1,2,1] sums to 6.",
    approach: "Kadane's: extend or restart the running sum, keep the max. O(n).",
  },
  6: {
    statement: "Find the contiguous subarray with the largest product.",
    input: "nums = [2,3,-2,4]",
    output: "6",
    why: "Subarray [2,3] gives the max product 6.",
    approach: "Track running max AND min (negatives flip sign). O(n).",
  },
  7: {
    statement: "Find the minimum element in a rotated sorted array of unique values.",
    input: "nums = [3,4,5,1,2]",
    output: "1",
    why: "The array was [1,2,3,4,5] rotated; the minimum is 1.",
    approach: "Binary search on the rotation point. O(log n).",
  },
  8: {
    statement: "Search a target in a rotated sorted array; return its index or −1.",
    input: "nums = [4,5,6,7,0,1,2], target = 0",
    output: "4",
    why: "0 sits at index 4.",
    approach: "Binary search deciding which half is sorted. O(log n).",
  },
  9: {
    statement: "Find all unique triplets that sum to zero.",
    input: "nums = [-1,0,1,2,-1,-4]",
    output: "[[-1,-1,2],[-1,0,1]]",
    why: "Both triplets sum to 0; duplicates are skipped.",
    approach: "Sort, then for each i use two pointers. O(n²).",
  },
  10: {
    statement: "Choose two lines so the container holds the most water.",
    input: "height = [1,8,6,2,5,4,8,3,7]",
    output: "49",
    why: "Lines at index 1 and 8: min(8,7)·7 = 49.",
    approach: "Two pointers from both ends, move the shorter wall in. O(n).",
  },
  11: {
    statement: "Move all zeroes to the end while keeping non-zero order; in place.",
    input: "nums = [0,1,0,3,12]",
    output: "[1,3,12,0,0]",
    why: "Non-zeros keep order; zeroes pushed to the back.",
    approach: "Write pointer for non-zeros, then fill rest with 0. O(n).",
  },
  12: {
    statement: "Remove duplicates from a sorted array in place; return new length.",
    input: "nums = [1,1,2]",
    output: "2  (nums = [1,2,...])",
    why: "Two unique values remain at the front.",
    approach: "Slow/fast pointers, copy when value changes. O(n).",
  },
  13: {
    statement: "Merge two sorted arrays into the first (which has trailing space).",
    input: "nums1 = [1,2,3,0,0,0], m=3, nums2 = [2,5,6], n=3",
    output: "[1,2,2,3,5,6]",
    why: "All six values merged in sorted order.",
    approach: "Fill from the back with two pointers. O(m+n).",
  },
  14: {
    statement: "Sort an array of 0s, 1s, and 2s in place (Dutch National Flag).",
    input: "nums = [2,0,2,1,1,0]",
    output: "[0,0,1,1,2,2]",
    why: "Colors grouped in order 0,1,2.",
    approach: "Three pointers low/mid/high, one pass. O(n).",
  },
  15: {
    statement: "Find a peak element (greater than its neighbours); return its index.",
    input: "nums = [1,2,3,1]",
    output: "2",
    why: "nums[2]=3 is greater than its neighbours.",
    approach: "Binary search toward the higher neighbour. O(log n).",
  },
  16: {
    statement: "Find the element appearing more than ⌊n/2⌋ times.",
    input: "nums = [2,2,1,1,1,2,2]",
    output: "2",
    why: "2 appears 4 times out of 7.",
    approach: "Boyer–Moore voting. O(n), O(1) space.",
  },
  17: {
    statement: "Rotate the array to the right by k steps, in place.",
    input: "nums = [1,2,3,4,5,6,7], k = 3",
    output: "[5,6,7,1,2,3,4]",
    why: "Last 3 elements wrap to the front.",
    approach: "Reverse whole, then reverse the two parts. O(n).",
  },
  18: {
    statement: "Find the missing number in 0..n.",
    input: "nums = [3,0,1]",
    output: "2",
    why: "Range 0..3 is missing 2.",
    approach: "XOR all indices and values, or sum formula. O(n).",
  },
  19: {
    statement: "Find all numbers in 1..n that do not appear in the array.",
    input: "nums = [4,3,2,7,8,2,3,1]",
    output: "[5,6]",
    why: "5 and 6 never appear.",
    approach: "Mark index num−1 negative, collect positive slots. O(n).",
  },
  20: {
    statement: "Every element appears twice except one; find the single one.",
    input: "nums = [4,1,2,1,2]",
    output: "4",
    why: "Only 4 is unpaired.",
    approach: "XOR all elements; pairs cancel. O(n), O(1).",
  },
  21: {
    statement: "Return the unique intersection of two arrays.",
    input: "nums1 = [1,2,2,1], nums2 = [2,2]",
    output: "[2]",
    why: "Only 2 is common; result is unique.",
    approach: "Two hash sets, intersect. O(n+m).",
  },
  22: {
    statement: "Return the intersection including duplicates (min count of each).",
    input: "nums1 = [1,2,2,1], nums2 = [2,2]",
    output: "[2,2]",
    why: "2 appears twice in both.",
    approach: "Count map of one array, decrement while scanning the other. O(n+m).",
  },
  23: {
    statement: "Rearrange numbers into the next lexicographically greater permutation.",
    input: "nums = [1,2,3]",
    output: "[1,3,2]",
    why: "Next bigger arrangement of the digits.",
    approach: "Find pivot, swap with next larger suffix value, reverse suffix. O(n).",
  },
  24: {
    statement: "Generate the first numRows of Pascal's triangle.",
    input: "numRows = 5",
    output: "[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]",
    why: "Each value is the sum of the two above it.",
    approach: "Build each row from the previous. O(n²).",
  },
  25: {
    statement: "Return only the kth (0-indexed) row of Pascal's triangle.",
    input: "rowIndex = 3",
    output: "[1,3,3,1]",
    why: "The 3rd row of the triangle.",
    approach: "Iterate one row using O(k) space. O(k²) time.",
  },
  26: {
    statement: "If a matrix cell is 0, set its entire row and column to 0, in place.",
    input: "[[1,1,1],[1,0,1],[1,1,1]]",
    output: "[[1,0,1],[0,0,0],[1,0,1]]",
    why: "The single 0 zeroes its row and column.",
    approach: "Use first row/col as markers. O(mn), O(1) space.",
  },
  27: {
    statement: "Return all matrix elements in spiral order.",
    input: "[[1,2,3],[4,5,6],[7,8,9]]",
    output: "[1,2,3,6,9,8,7,4,5]",
    why: "Walk the border inward clockwise.",
    approach: "Track four shrinking boundaries. O(mn).",
  },
  28: {
    statement: "Rotate an n×n image 90° clockwise, in place.",
    input: "[[1,2,3],[4,5,6],[7,8,9]]",
    output: "[[7,4,1],[8,5,2],[9,6,3]]",
    why: "Each column becomes a row.",
    approach: "Transpose, then reverse each row. O(n²).",
  },
  29: {
    statement: "Find the smallest missing positive integer.",
    input: "nums = [3,4,-1,1]",
    output: "2",
    why: "1 is present, 2 is the first positive missing.",
    approach: "Place each value at index value−1, then scan. O(n), O(1).",
  },
  30: {
    statement: "Length of the longest run of consecutive integers.",
    input: "nums = [100,4,200,1,3,2]",
    output: "4",
    why: "1,2,3,4 is the longest consecutive sequence.",
    approach: "Hash set; start counting only at sequence beginnings. O(n).",
  },
  31: {
    statement: "Find the kth largest element in an array.",
    input: "nums = [3,2,1,5,6,4], k = 2",
    output: "5",
    why: "Sorted desc: 6,5,... the 2nd largest is 5.",
    approach: "Min-heap of size k, or Quickselect. O(n) avg.",
  },
  32: {
    statement: "Count contiguous subarrays whose sum equals k.",
    input: "nums = [1,1,1], k = 2",
    output: "2",
    why: "Two subarrays [1,1] sum to 2.",
    approach: "Prefix-sum counts in a hash map. O(n).",
  },
  33: {
    statement: "Find the one repeated number in 1..n (array length n+1), without modifying it.",
    input: "nums = [1,3,4,2,2]",
    output: "2",
    why: "2 is the duplicated value.",
    approach: "Floyd cycle detection on value→index. O(n), O(1).",
  },
  34: {
    statement: "Compute how much rain water is trapped between bars.",
    input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]",
    output: "6",
    why: "Water pools in the dips between taller bars.",
    approach: "Two pointers tracking left/right max. O(n).",
  },
  35: {
    statement: "Return the max of each sliding window of size k.",
    input: "nums = [1,3,-1,-3,5,3,6,7], k = 3",
    output: "[3,3,5,5,6,7]",
    why: "Maximum within each consecutive window of 3.",
    approach: "Monotonic decreasing deque of indices. O(n).",
  },
  // ===== 2. Strings =====
  36: {
    statement: "Check if a string is a palindrome, considering only alphanumerics and ignoring case.",
    input: '"A man, a plan, a canal: Panama"',
    output: "true",
    why: "Cleaned text reads the same both ways.",
    approach: "Two pointers skipping non-alphanumerics. O(n).",
  },
  37: {
    statement: "Length of the longest substring without repeating characters.",
    input: '"abcabcbb"',
    output: "3",
    why: '"abc" is the longest unique-character window.',
    approach: "Sliding window with a last-seen index map. O(n).",
  },
  38: {
    statement: "Longest substring of one repeated letter after at most k replacements.",
    input: 's = "AABABBA", k = 1',
    output: "4",
    why: "Replace one char to get \"AABA\"→\"AAAA\"-style run of 4.",
    approach: "Sliding window tracking the most frequent char. O(n).",
  },
  39: {
    statement: "Determine if brackets ()[]{} are validly opened and closed.",
    input: '"()[]{}"',
    output: "true",
    why: "Every bracket is matched in the right order.",
    approach: "Stack: push openers, match on closers. O(n).",
  },
  40: {
    statement: "Find the longest palindromic substring.",
    input: '"babad"',
    output: '"bab"  (or "aba")',
    why: "Both are valid longest palindromes of length 3.",
    approach: "Expand around each center. O(n²).",
  },
  41: {
    statement: "Count the palindromic substrings in a string.",
    input: '"aaa"',
    output: "6",
    why: '"a"×3, "aa"×2, "aaa"×1 = 6.',
    approach: "Expand around each center, count hits. O(n²).",
  },
  42: {
    statement: "Encode a list of strings to one string and decode it back.",
    input: '["lint","code"]',
    output: '"4#lint4#code" → ["lint","code"]',
    why: "Length-prefixing makes any character safe to decode.",
    approach: "Prefix each with length + delimiter. O(n).",
  },
  43: {
    statement: "Group words that are anagrams of each other.",
    input: '["eat","tea","tan","ate","nat","bat"]',
    output: '[["eat","tea","ate"],["tan","nat"],["bat"]]',
    why: "Words sharing the same letters are grouped.",
    approach: "Hash map keyed by sorted word or char counts. O(n·k).",
  },
  44: {
    statement: "Find all start indices of p's anagrams in s.",
    input: 's = "cbaebabacd", p = "abc"',
    output: "[0,6]",
    why: '"cba" (idx 0) and "bac" (idx 6) are anagrams of "abc".',
    approach: "Sliding window of frequency counts. O(n).",
  },
  45: {
    statement: "Smallest substring of s containing all characters of t.",
    input: 's = "ADOBECODEBANC", t = "ABC"',
    output: '"BANC"',
    why: "Shortest window covering A, B, and C.",
    approach: "Sliding window with need/have counts. O(n).",
  },
  46: {
    statement: "Reverse a character array in place.",
    input: '["h","e","l","l","o"]',
    output: '["o","l","l","e","h"]',
    why: "Characters reversed end to end.",
    approach: "Two pointers swapping inward. O(n).",
  },
  47: {
    statement: "Reverse only the vowels of a string.",
    input: '"hello"',
    output: '"holle"',
    why: "Vowels e and o swap; consonants stay.",
    approach: "Two pointers stopping on vowels. O(n).",
  },
  48: {
    statement: "Reverse the order of words, trimming extra spaces.",
    input: '"  the sky is blue  "',
    output: '"blue is sky the"',
    why: "Words reversed; surrounding/extra spaces removed.",
    approach: "Split on whitespace, reverse, join. O(n).",
  },
  49: {
    statement: "Convert a string to a 32-bit signed integer (atoi rules).",
    input: '"   -42"',
    output: "-42",
    why: "Skip spaces, read sign and digits, clamp to int range.",
    approach: "Linear parse handling sign, digits, overflow. O(n).",
  },
  50: {
    statement: "Return the index of the first occurrence of needle in haystack, or −1.",
    input: 'haystack = "sadbutsad", needle = "sad"',
    output: "0",
    why: '"sad" first appears at index 0.',
    approach: "KMP for O(n+m), or built-in scan.",
  },
  51: {
    statement: "Find the longest common prefix among an array of strings.",
    input: '["flower","flow","flight"]',
    output: '"fl"',
    why: "All three share the prefix \"fl\".",
    approach: "Compare characters column by column. O(total chars).",
  },
  52: {
    statement: "Check if two strings are anagrams.",
    input: 's = "anagram", t = "nagaram"',
    output: "true",
    why: "Both have identical letter counts.",
    approach: "Compare frequency counts. O(n).",
  },
  53: {
    statement: "Check if two strings are isomorphic (consistent char mapping).",
    input: 's = "egg", t = "add"',
    output: "true",
    why: "e→a, g→d maps consistently both ways.",
    approach: "Two maps for forward/backward consistency. O(n).",
  },
  54: {
    statement: "Check if a string follows a pattern (bijection word↔letter).",
    input: 'pattern = "abba", s = "dog cat cat dog"',
    output: "true",
    why: "a↔dog, b↔cat holds throughout.",
    approach: "Two hash maps for the bijection. O(n).",
  },
  55: {
    statement: "Check if two arrays of strings spell the same combined text.",
    input: 'word1 = ["ab","c"], word2 = ["a","bc"]',
    output: "true",
    why: 'Both concatenate to "abc".',
    approach: "Compare character streams with two pointers. O(n).",
  },
  56: {
    statement: "Generate the nth term of the count-and-say sequence.",
    input: "n = 4",
    output: '"1211"',
    why: '1 → "11" → "21" → "1211" by reading run lengths.',
    approach: "Iteratively run-length encode the previous term. O(n·len).",
  },
  57: {
    statement: "Multiply two non-negative numbers given as strings.",
    input: 'num1 = "123", num2 = "456"',
    output: '"56088"',
    why: "123 × 456 = 56088.",
    approach: "Grade-school multiply into a digit array. O(m·n).",
  },
  58: {
    statement: "Add two non-negative numbers given as strings.",
    input: 'num1 = "11", num2 = "123"',
    output: '"134"',
    why: "11 + 123 = 134.",
    approach: "Add digit by digit from the right with carry. O(max len).",
  },
  59: {
    statement: "Add two binary strings.",
    input: 'a = "11", b = "1"',
    output: '"100"',
    why: "3 + 1 = 4 = binary 100.",
    approach: "Bitwise add from the right with carry. O(max len).",
  },
  60: {
    statement: "Convert a Roman numeral to an integer.",
    input: '"MCMXCIV"',
    output: "1994",
    why: "M(1000)+CM(900)+XC(90)+IV(4).",
    approach: "Subtract when a smaller symbol precedes a larger one. O(n).",
  },
  61: {
    statement: "Convert an integer to a Roman numeral.",
    input: "num = 1994",
    output: '"MCMXCIV"',
    why: "1994 decomposes into M, CM, XC, IV.",
    approach: "Greedy with value→symbol table. O(1).",
  },
  62: {
    statement: "Minimum insertions to make parentheses valid.",
    input: '"())"',
    output: "1",
    why: "Add one '(' to balance the extra ')'.",
    approach: "Track open balance and needed inserts. O(n).",
  },
  63: {
    statement: "Generate all valid combinations of n pairs of parentheses.",
    input: "n = 3",
    output: '["((()))","(()())","(())()","()(())","()()()"]',
    why: "All balanced arrangements of 3 pairs.",
    approach: "Backtracking with open/close counts. O(4ⁿ/√n).",
  },
  64: {
    statement: "Decode a string with k[encoded] repetition syntax.",
    input: '"3[a2[c]]"',
    output: '"accaccacc"',
    why: '2[c]="cc", then 3[acc]="accaccacc".',
    approach: "Stack of counts and partial strings. O(output len).",
  },
  65: {
    statement: "Length of the longest valid (well-formed) parentheses substring.",
    input: '")()())"',
    output: "4",
    why: '"()()" in the middle is the longest valid run.',
    approach: "Stack of indices, or DP. O(n).",
  },
  66: {
    statement: "Minimum edits (insert/delete/replace) to turn word1 into word2.",
    input: 'word1 = "horse", word2 = "ros"',
    output: "3",
    why: "horse→rorse→rose→ros (replace, delete, delete).",
    approach: "2-D DP edit-distance table. O(m·n).",
  },
  67: {
    statement: "Implement regex matching with '.' and '*'.",
    input: 's = "aab", p = "c*a*b"',
    output: "true",
    why: 'c* matches empty, a* matches "aa", b matches "b".',
    approach: "DP over (i,j) match table. O(m·n).",
  },
  68: {
    statement: "Implement wildcard matching with '?' and '*'.",
    input: 's = "adceb", p = "*a*b"',
    output: "true",
    why: "* segments absorb the gaps around a and b.",
    approach: "DP, or greedy with last-star backtrack. O(m·n).",
  },
  69: {
    statement: "Count distinct subsequences of s that equal t.",
    input: 's = "rabbbit", t = "rabbit"',
    output: "3",
    why: "Three ways to pick \"rabbit\" from the b's.",
    approach: "2-D DP counting matches. O(m·n).",
  },
  70: {
    statement: "Return the index of the first occurrence of needle in haystack.",
    input: 'haystack = "leetcode", needle = "leeto"',
    output: "-1",
    why: '"leeto" never appears in "leetcode".',
    approach: "KMP for O(n+m), or substring scan.",
  },
  // ===== 3. Linked Lists =====
  71: {
    statement: "Reverse a singly linked list.",
    input: "1→2→3→4→5",
    output: "5→4→3→2→1",
    why: "Pointers flipped end to end.",
    approach: "Iteratively re-point prev/curr. O(n), O(1).",
  },
  72: {
    statement: "Merge two sorted linked lists into one sorted list.",
    input: "1→2→4, 1→3→4",
    output: "1→1→2→3→4→4",
    why: "All nodes spliced in sorted order.",
    approach: "Dummy head, splice the smaller head each step. O(n+m).",
  },
  73: {
    statement: "Reorder list L0→L1→…→Ln as L0→Ln→L1→Ln-1→…",
    input: "1→2→3→4",
    output: "1→4→2→3",
    why: "Front and back interleaved.",
    approach: "Find middle, reverse second half, merge. O(n).",
  },
  74: {
    statement: "Remove the nth node from the end of the list.",
    input: "1→2→3→4→5, n = 2",
    output: "1→2→3→5",
    why: "The 2nd-from-end node (4) is removed.",
    approach: "Two pointers n apart, one pass. O(n).",
  },
  75: {
    statement: "Deep-copy a list whose nodes also have a random pointer.",
    input: "nodes with next + random links",
    output: "an independent identical list",
    why: "Clone preserves both next and random topology.",
    approach: "Interleave clones, set randoms, split. O(n).",
  },
  76: {
    statement: "Add two numbers stored as reversed digit lists.",
    input: "(2→4→3) + (5→6→4)",
    output: "7→0→8",
    why: "342 + 465 = 807, stored reversed.",
    approach: "Add node by node with carry. O(max len).",
  },
  77: {
    statement: "Detect whether a linked list has a cycle.",
    input: "3→2→0→-4→(back to 2)",
    output: "true",
    why: "The tail links back into the list.",
    approach: "Floyd slow/fast pointers meet inside a cycle. O(n).",
  },
  78: {
    statement: "Return the node where the cycle begins, or null.",
    input: "3→2→0→-4→(back to 2)",
    output: "node with value 2",
    why: "The cycle starts at the node valued 2.",
    approach: "Floyd meet, then advance from head and meet point. O(n).",
  },
  79: {
    statement: "Find the duplicate number using cycle detection on indices.",
    input: "nums = [1,3,4,2,2]",
    output: "2",
    why: "Treating values as next-pointers forms a cycle at 2.",
    approach: "Floyd cycle detection on value→index. O(n), O(1).",
  },
  80: {
    statement: "Merge k sorted linked lists into one.",
    input: "[1→4→5, 1→3→4, 2→6]",
    output: "1→1→2→3→4→4→5→6",
    why: "All lists merged in sorted order.",
    approach: "Min-heap of heads, or pairwise merge. O(N log k).",
  },
  81: {
    statement: "Reverse the list nodes k at a time.",
    input: "1→2→3→4→5, k = 2",
    output: "2→1→4→3→5",
    why: "Each group of 2 reversed; leftover stays.",
    approach: "Reverse each k-block, link blocks. O(n).",
  },
  82: {
    statement: "Check if a linked list is a palindrome.",
    input: "1→2→2→1",
    output: "true",
    why: "Reads the same forwards and backwards.",
    approach: "Find middle, reverse half, compare. O(n), O(1).",
  },
  83: {
    statement: "Find the node where two lists intersect, or null.",
    input: "two lists sharing a tail at 8",
    output: "node with value 8",
    why: "Both lists merge at the node valued 8.",
    approach: "Two pointers swapping lists equalize lengths. O(n+m).",
  },
  84: {
    statement: "Return the middle node (second middle if even length).",
    input: "1→2→3→4→5",
    output: "3→4→5  (node 3)",
    why: "Node 3 is the middle of five nodes.",
    approach: "Slow/fast pointers. O(n).",
  },
  85: {
    statement: "Delete a node given only access to that node (not the head).",
    input: "list 4→5→1→9, node = 5",
    output: "4→1→9",
    why: "Node 5 removed by copying the next node into it.",
    approach: "Copy next node's value and bypass it. O(1).",
  },
  86: {
    statement: "Remove all nodes equal to a given value.",
    input: "1→2→6→3→4→5→6, val = 6",
    output: "1→2→3→4→5",
    why: "Both 6 nodes removed.",
    approach: "Dummy head, skip matching nodes. O(n).",
  },
  87: {
    statement: "Group nodes at odd indices, then nodes at even indices.",
    input: "1→2→3→4→5",
    output: "1→3→5→2→4",
    why: "Odd-position nodes first, then even.",
    approach: "Weave two pointers, then join. O(n).",
  },
  88: {
    statement: "Sort a linked list in O(n log n).",
    input: "4→2→1→3",
    output: "1→2→3→4",
    why: "Nodes arranged in ascending order.",
    approach: "Merge sort on the list. O(n log n).",
  },
  89: {
    statement: "Partition list so nodes < x come before nodes ≥ x (stable).",
    input: "1→4→3→2→5→2, x = 3",
    output: "1→2→2→4→3→5",
    why: "Values < 3 kept before the rest, order preserved.",
    approach: "Two dummy lists, then concatenate. O(n).",
  },
  90: {
    statement: "Rotate the list to the right by k places.",
    input: "1→2→3→4→5, k = 2",
    output: "4→5→1→2→3",
    why: "Last 2 nodes moved to the front.",
    approach: "Close into a ring, cut at the right spot. O(n).",
  },
  91: {
    statement: "Swap every two adjacent nodes.",
    input: "1→2→3→4",
    output: "2→1→4→3",
    why: "Each adjacent pair is swapped.",
    approach: "Dummy head, relink in pairs. O(n).",
  },
  92: {
    statement: "Reverse the nodes from position left to right.",
    input: "1→2→3→4→5, left=2, right=4",
    output: "1→4→3→2→5",
    why: "Only the 2nd–4th nodes are reversed.",
    approach: "Reverse the sublist in one pass. O(n).",
  },
  93: {
    statement: "Flatten a multilevel doubly linked list into a single level.",
    input: "nodes with next + child links",
    output: "flat next-only list (child branches inlined)",
    why: "Each child sublist is spliced in after its parent.",
    approach: "DFS/stack, splice children inline. O(n).",
  },
  94: {
    statement: "Design an LRU cache with O(1) get and put.",
    input: "capacity 2; put(1,1),put(2,2),get(1),put(3,3),get(2)",
    output: "get(1)=1, get(2)=-1",
    why: "Putting 3 evicts least-recently-used key 2.",
    approach: "Hash map + doubly linked list. O(1) ops.",
  },
  95: {
    statement: "Design an LFU cache with O(1) get and put.",
    input: "capacity 2; mixed get/put with frequencies",
    output: "evicts the least-frequently-used (ties: least recent)",
    why: "Lowest use-count key is removed first.",
    approach: "Hash maps keyed by frequency buckets. O(1) ops.",
  },
  // ===== 4. Stacks & Queues =====
  96: {
    statement: "Implement a FIFO queue using only two stacks.",
    input: "push(1),push(2),peek(),pop(),empty()",
    output: "peek=1, pop=1, empty=false",
    why: "Queue order preserved despite stack storage.",
    approach: "In-stack + out-stack; move on demand. Amortized O(1).",
  },
  97: {
    statement: "Implement a LIFO stack using only queues.",
    input: "push(1),push(2),top(),pop(),empty()",
    output: "top=2, pop=2, empty=false",
    why: "Stack order preserved using queue rotations.",
    approach: "Rotate queue on push so newest is at front. O(n) push.",
  },
  98: {
    statement: "Stack with push/pop/top and O(1) getMin.",
    input: "push(-2),push(0),push(-3),getMin(),pop(),top(),getMin()",
    output: "getMin=-3, top=0, getMin=-2",
    why: "Min tracked alongside each push.",
    approach: "Auxiliary stack of running minimums. O(1) ops.",
  },
  99: {
    statement: "Evaluate an expression in Reverse Polish Notation.",
    input: '["2","1","+","3","*"]',
    output: "9",
    why: "(2 + 1) × 3 = 9.",
    approach: "Stack: push operands, apply operators. O(n).",
  },
  100: {
    statement: "For each day, how many days until a warmer temperature.",
    input: "[73,74,75,71,69,72,76,73]",
    output: "[1,1,4,2,1,1,0,0]",
    why: "e.g. day 0 (73) waits 1 day for 74.",
    approach: "Monotonic decreasing stack of indices. O(n).",
  },
  101: {
    statement: "Next greater element for nums1 values, found within nums2.",
    input: "nums1 = [4,1,2], nums2 = [1,3,4,2]",
    output: "[-1,3,-1]",
    why: "4 has none after it; 1's next greater is 3.",
    approach: "Monotonic stack over nums2 + lookup map. O(n).",
  },
  102: {
    statement: "Next greater element in a circular array.",
    input: "[1,2,1]",
    output: "[2,-1,2]",
    why: "Last 1 wraps around to find 2.",
    approach: "Monotonic stack over 2× the array. O(n).",
  },
  103: {
    statement: "Largest rectangle area in a histogram.",
    input: "heights = [2,1,5,6,2,3]",
    output: "10",
    why: "Bars 5 and 6 form a 2×5 = 10 rectangle.",
    approach: "Monotonic increasing stack of indices. O(n).",
  },
  104: {
    statement: "Largest rectangle of 1s in a binary matrix.",
    input: "rows of 0/1 (e.g. a 4×5 grid)",
    output: "6",
    why: "The biggest all-1s rectangle has area 6.",
    approach: "Per-row histogram + largest-rectangle. O(mn).",
  },
  105: {
    statement: "Maximum of every sliding window of size k.",
    input: "nums = [1,3,-1,-3,5,3,6,7], k = 3",
    output: "[3,3,5,5,6,7]",
    why: "Max within each window of 3.",
    approach: "Monotonic decreasing deque of indices. O(n).",
  },
  106: {
    statement: "Design StockSpanner: count of consecutive days ≤ today's price.",
    input: "next([100,80,60,70,60,75,85])",
    output: "[1,1,1,2,1,4,6]",
    why: "75 spans 4 days (60,70,60,75) ≤ 75.",
    approach: "Monotonic stack of (price, span). Amortized O(1).",
  },
  107: {
    statement: "Online stock span (streaming version of the span problem).",
    input: "prices arriving one by one",
    output: "span for each new price",
    why: "Counts back-run of prices not exceeding today's.",
    approach: "Monotonic stack of (price, span). Amortized O(1).",
  },
  108: {
    statement: "Remove k digits to make the smallest possible number.",
    input: 'num = "1432219", k = 3',
    output: '"1219"',
    why: "Dropping 4,3,2 yields the minimum.",
    approach: "Monotonic increasing stack, drop bigger leading digits. O(n).",
  },
  109: {
    statement: "Detect a 132 pattern (i<j<k with nums[i]<nums[k]<nums[j]).",
    input: "[3,1,4,2]",
    output: "true",
    why: "1 < 2 < 4 forms a 1-3-2 pattern.",
    approach: "Reverse scan with a stack tracking the '2'. O(n).",
  },
  110: {
    statement: "Design a fixed-size circular queue.",
    input: "k=3; enQueue 1,2,3; enQueue 4; Rear; isFull; deQueue; enQueue 4; Rear",
    output: "enQueue(4)=false then true, Rear=4, isFull=true",
    why: "Wraps around the fixed buffer.",
    approach: "Array with head/tail indices modulo k. O(1) ops.",
  },
  // ===== 5. Trees & Tries =====
  111: {
    statement: "Find the maximum depth of a binary tree.",
    input: "[3,9,20,null,null,15,7]",
    output: "3",
    why: "Longest root-to-leaf path has 3 nodes.",
    approach: "DFS: 1 + max(left, right). O(n).",
  },
  112: {
    statement: "Check whether two binary trees are identical.",
    input: "p = [1,2,3], q = [1,2,3]",
    output: "true",
    why: "Same structure and same values.",
    approach: "Recurse comparing nodes in lockstep. O(n).",
  },
  113: {
    statement: "Invert (mirror) a binary tree.",
    input: "[4,2,7,1,3,6,9]",
    output: "[4,7,2,9,6,3,1]",
    why: "Left and right children swapped at every node.",
    approach: "Recurse swapping children. O(n).",
  },
  114: {
    statement: "Maximum path sum between any two nodes.",
    input: "[-10,9,20,null,null,15,7]",
    output: "42",
    why: "Path 15→20→7 sums to 42.",
    approach: "DFS returning best downward gain, track global max. O(n).",
  },
  115: {
    statement: "Return node values level by level (top to bottom).",
    input: "[3,9,20,null,null,15,7]",
    output: "[[3],[9,20],[15,7]]",
    why: "Each sublist is one tree level.",
    approach: "BFS with a queue per level. O(n).",
  },
  116: {
    statement: "Serialize a binary tree to a string and back.",
    input: "[1,2,3,null,null,4,5]",
    output: "round-trips to the same tree",
    why: "Encoding captures structure including nulls.",
    approach: "Preorder with null markers. O(n).",
  },
  117: {
    statement: "Check if one tree is a subtree of another.",
    input: "root = [3,4,5,1,2], subRoot = [4,1,2]",
    output: "true",
    why: "The subtree rooted at 4 matches exactly.",
    approach: "At each node test sameTree(sub). O(m·n).",
  },
  118: {
    statement: "Build a binary tree from preorder and inorder traversals.",
    input: "preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]",
    output: "[3,9,20,null,null,15,7]",
    why: "Preorder gives roots; inorder splits subtrees.",
    approach: "Recurse using an inorder index map. O(n).",
  },
  119: {
    statement: "Validate that a binary tree is a BST.",
    input: "[2,1,3]",
    output: "true",
    why: "1 < 2 < 3 satisfies BST order.",
    approach: "DFS passing (min,max) bounds. O(n).",
  },
  120: {
    statement: "Find the kth smallest value in a BST.",
    input: "root = [3,1,4,null,2], k = 1",
    output: "1",
    why: "Inorder order is 1,2,3,4; 1st is 1.",
    approach: "Inorder traversal, stop at k. O(h+k).",
  },
  121: {
    statement: "Lowest common ancestor of two nodes in a BST.",
    input: "root = [6,2,8,...], p = 2, q = 8",
    output: "6",
    why: "2 and 8 split at the root 6.",
    approach: "Walk down: go left/right by value, split = LCA. O(h).",
  },
  122: {
    statement: "Lowest common ancestor of two nodes in a binary tree.",
    input: "root = [3,5,1,...], p = 5, q = 1",
    output: "3",
    why: "5 and 1 first meet at the root 3.",
    approach: "DFS; node where both sides return non-null. O(n).",
  },
  123: {
    statement: "Implement a trie with insert, search, startsWith.",
    input: 'insert("apple"); search("app"); startsWith("app")',
    output: "search=false, startsWith=true",
    why: '"app" is a prefix but not a full inserted word.',
    approach: "Node tree of children + end flag. O(len) ops.",
  },
  124: {
    statement: "Word dictionary supporting '.' wildcard search.",
    input: 'addWord("bad"); search("b.d")',
    output: "true",
    why: "'.' matches any single character.",
    approach: "Trie with DFS on wildcards. O(len) / O(26^dots).",
  },
  125: {
    statement: "Find all dictionary words present in a character board.",
    input: "board grid + words = [\"oath\",\"pea\",\"eat\",\"rain\"]",
    output: '["eat","oath"]',
    why: "Only those two words can be traced on the board.",
    approach: "Trie of words + DFS backtracking on the grid. O(cells·paths).",
  },
  126: {
    statement: "Return the values visible from the right side of the tree.",
    input: "[1,2,3,null,5,null,4]",
    output: "[1,3,4]",
    why: "Rightmost node at each level.",
    approach: "BFS taking the last node per level. O(n).",
  },
  127: {
    statement: "Level-order traversal alternating left→right and right→left.",
    input: "[3,9,20,null,null,15,7]",
    output: "[[3],[20,9],[15,7]]",
    why: "Every other level is reversed.",
    approach: "BFS with a level-parity flip. O(n).",
  },
  128: {
    statement: "Check if a binary tree is height-balanced.",
    input: "[3,9,20,null,null,15,7]",
    output: "true",
    why: "Every node's subtree heights differ by ≤ 1.",
    approach: "DFS returning height, −1 signals imbalance. O(n).",
  },
  129: {
    statement: "Find the minimum depth to a leaf.",
    input: "[2,null,3,null,4,null,5,null,6]",
    output: "5",
    why: "Only one path to a leaf, length 5.",
    approach: "BFS stops at the first leaf. O(n).",
  },
  130: {
    statement: "Does a root-to-leaf path sum to targetSum?",
    input: "root sum tree, targetSum = 22",
    output: "true",
    why: "Some root-to-leaf path adds up to 22.",
    approach: "DFS subtracting node values to leaves. O(n).",
  },
  131: {
    statement: "Return all root-to-leaf paths summing to targetSum.",
    input: "targetSum = 22",
    output: "[[5,4,11,2],[5,8,4,5]]",
    why: "Both listed paths total 22.",
    approach: "DFS backtracking, record matching paths. O(n²).",
  },
  132: {
    statement: "Count downward paths (any start/end) summing to a target.",
    input: "targetSum = 8",
    output: "3",
    why: "Three distinct downward paths total 8.",
    approach: "Prefix-sum counts along DFS. O(n).",
  },
  133: {
    statement: "Length of the longest path between any two nodes (edges).",
    input: "[1,2,3,4,5]",
    output: "3",
    why: "Path 4→2→1→3 has 3 edges.",
    approach: "DFS returning depth, track left+right max. O(n).",
  },
  134: {
    statement: "Merge two binary trees by summing overlapping nodes.",
    input: "[1,3,2,5] and [2,1,3,null,4,null,7]",
    output: "[3,4,5,5,4,null,7]",
    why: "Overlapping nodes are added together.",
    approach: "Recurse summing matching nodes. O(n).",
  },
  135: {
    statement: "Check if a tree is a mirror of itself.",
    input: "[1,2,2,3,4,4,3]",
    output: "true",
    why: "Left and right subtrees are mirror images.",
    approach: "Recurse comparing mirrored children. O(n).",
  },
  136: {
    statement: "Convert a sorted array into a height-balanced BST.",
    input: "[-10,-3,0,5,9]",
    output: "[0,-3,9,-10,null,5]  (a valid balanced BST)",
    why: "Middle element becomes the root recursively.",
    approach: "Pick mid as root, recurse halves. O(n).",
  },
  137: {
    statement: "Flatten a binary tree into a right-leaning linked list (preorder).",
    input: "[1,2,5,3,4,null,6]",
    output: "1→2→3→4→5→6 (all via right child)",
    why: "Preorder sequence linked through right pointers.",
    approach: "Reverse-preorder rewiring, or Morris. O(n).",
  },
  138: {
    statement: "Populate each node's next pointer to its right neighbour.",
    input: "perfect tree [1,2,3,4,5,6,7]",
    output: "level lists linked via next, ending at null",
    why: "Each node points to the next node on its level.",
    approach: "Use established next links level by level. O(n), O(1).",
  },
  139: {
    statement: "BST iterator with next() and hasNext() in inorder.",
    input: "next(),next(),hasNext(),next()...",
    output: "ascending values on demand",
    why: "Yields BST values in sorted order.",
    approach: "Controlled inorder with a stack. Amortized O(1).",
  },
  140: {
    statement: "Insert a value into a BST keeping it valid.",
    input: "root = [4,2,7,1,3], val = 5",
    output: "[4,2,7,1,3,5]",
    why: "5 attaches as the left child of 7.",
    approach: "Walk down to the correct empty slot. O(h).",
  },
  141: {
    statement: "Delete a node from a BST keeping it valid.",
    input: "root = [5,3,6,2,4,null,7], key = 3",
    output: "a valid BST without 3 (e.g. successor replaces it)",
    why: "Node replaced by its inorder successor.",
    approach: "Find node, splice or swap with successor. O(h).",
  },
  142: {
    statement: "All node values at distance k from a target node.",
    input: "target = 5, k = 2",
    output: "[7,4,1]",
    why: "Nodes exactly 2 edges from node 5.",
    approach: "Build parent links, BFS k levels out. O(n).",
  },
  143: {
    statement: "Maximum path sum between any two nodes (revisited).",
    input: "[-10,9,20,null,null,15,7]",
    output: "42",
    why: "Path 15→20→7 sums to 42.",
    approach: "DFS best downward gain, track global max. O(n).",
  },
  144: {
    statement: "Count the nodes of a complete binary tree faster than O(n).",
    input: "[1,2,3,4,5,6]",
    output: "6",
    why: "The complete tree has 6 nodes.",
    approach: "Compare left/right heights, recurse. O(log²n).",
  },
  145: {
    statement: "Serialize and deserialize a BST compactly.",
    input: "[2,1,3]",
    output: "round-trips to the same BST",
    why: "BST order lets you skip null markers.",
    approach: "Preorder + bounds rebuild. O(n).",
  },
  // ===== 6. Graphs =====
  146: {
    statement: "Count the islands ('1' land) in a grid.",
    input: '[["1","1","0"],["1","0","0"],["0","0","1"]]',
    output: "2",
    why: "One connected landmass top-left, one bottom-right.",
    approach: "DFS/BFS flood fill each unvisited land cell. O(mn).",
  },
  147: {
    statement: "Deep-copy a connected undirected graph.",
    input: "adjacency list of a graph",
    output: "an independent identical graph",
    why: "Clone preserves nodes and all edges.",
    approach: "DFS/BFS with an original→clone map. O(V+E).",
  },
  148: {
    statement: "Area of the largest island in a grid.",
    input: "a grid of 0/1 cells",
    output: "6",
    why: "The biggest connected 1-region has 6 cells.",
    approach: "DFS counting cells per island. O(mn).",
  },
  149: {
    statement: "Cells from which water can flow to both oceans.",
    input: "a height grid bordered by Pacific & Atlantic",
    output: "list of [row,col] reaching both",
    why: "Water flows downhill to each ocean from these cells.",
    approach: "BFS/DFS inward from both ocean borders, intersect. O(mn).",
  },
  150: {
    statement: "Capture regions of 'O' fully surrounded by 'X'.",
    input: "board of X/O",
    output: "border-connected O kept, the rest flipped to X",
    why: "Only O's touching an edge survive.",
    approach: "Mark border-connected O's, flip the rest. O(mn).",
  },
  151: {
    statement: "Minutes until all fresh oranges rot (4-dir spread).",
    input: "[[2,1,1],[1,1,0],[0,1,1]]",
    output: "4",
    why: "Rot spreads outward, last orange rots at minute 4.",
    approach: "Multi-source BFS from rotten oranges. O(mn).",
  },
  152: {
    statement: "Fill each empty room with distance to its nearest gate.",
    input: "grid of gates(0), walls(-1), empty(INF)",
    output: "each empty cell = steps to nearest gate",
    why: "Distances spread out from all gates.",
    approach: "Multi-source BFS from all gates. O(mn).",
  },
  153: {
    statement: "Can all courses be finished given prerequisites?",
    input: "numCourses=2, prereq=[[1,0]]",
    output: "true",
    why: "Take 0 then 1; no cycle.",
    approach: "Topological sort / cycle detection. O(V+E).",
  },
  154: {
    statement: "Return a valid order to finish all courses.",
    input: "numCourses=4, prereq=[[1,0],[2,0],[3,1],[3,2]]",
    output: "[0,1,2,3]",
    why: "An order respecting all prerequisites.",
    approach: "Kahn's BFS topological sort. O(V+E).",
  },
  155: {
    statement: "Find the edge that turns a tree into a graph with a cycle.",
    input: "edges = [[1,2],[1,3],[2,3]]",
    output: "[2,3]",
    why: "[2,3] is the last edge closing a cycle.",
    approach: "Union-Find; first edge joining same set. O(n·α).",
  },
  156: {
    statement: "Count connected components in an undirected graph.",
    input: "n=5, edges=[[0,1],[1,2],[3,4]]",
    output: "2",
    why: "{0,1,2} and {3,4} are two components.",
    approach: "Union-Find or DFS counting. O(V+E).",
  },
  157: {
    statement: "Check if edges form a valid tree (connected, no cycle).",
    input: "n=5, edges=[[0,1],[0,2],[0,3],[1,4]]",
    output: "true",
    why: "n−1 edges, fully connected, acyclic.",
    approach: "Union-Find: n−1 edges and all merge. O(n·α).",
  },
  158: {
    statement: "Shortest transform length from beginWord to endWord, one letter at a time.",
    input: 'begin="hit", end="cog", words=["hot","dot","dog","lot","log","cog"]',
    output: "5",
    why: "hit→hot→dot→dog→cog is 5 words.",
    approach: "BFS over one-letter-different neighbours. O(N·L·26).",
  },
  159: {
    statement: "Find roots that minimize the tree's height.",
    input: "n=4, edges=[[1,0],[1,2],[1,3]]",
    output: "[1]",
    why: "Rooting at 1 gives the smallest height.",
    approach: "Trim leaves layer by layer to the center. O(V+E).",
  },
  160: {
    statement: "Check whether a graph is bipartite (2-colorable).",
    input: "graph = [[1,3],[0,2],[1,3],[0,2]]",
    output: "true",
    why: "Nodes split into two conflict-free groups.",
    approach: "BFS/DFS 2-coloring. O(V+E).",
  },
  161: {
    statement: "Time for a signal to reach all nodes from source k.",
    input: "times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2",
    output: "2",
    why: "Farthest node (4) is reached at time 2.",
    approach: "Dijkstra from k; answer = max distance. O(E log V).",
  },
  162: {
    statement: "Cheapest price from src to dst with at most k stops.",
    input: "flights, src=0, dst=3, k=1",
    output: "cheapest cost within k stops (e.g. 700)",
    why: "Within the stop limit, this is the lowest fare.",
    approach: "Bellman-Ford limited to k+1 relaxations. O(k·E).",
  },
  163: {
    statement: "Answer division queries using known a/b ratios.",
    input: "a/b=2, b/c=3; query a/c, b/a",
    output: "[6.0, 0.5]",
    why: "a/c = 2·3 = 6; b/a = 1/2.",
    approach: "Build weighted graph, DFS multiply along path. O(Q·V).",
  },
  164: {
    statement: "Find nodes from which every path reaches a terminal (no cycles).",
    input: "graph = [[1,2],[2,3],[5],[0],[5],[],[]]",
    output: "[2,4,5,6]",
    why: "These nodes avoid all cycles.",
    approach: "Reverse topological / cycle coloring. O(V+E).",
  },
  165: {
    statement: "Derive character order from a sorted alien dictionary.",
    input: '["wrt","wrf","er","ett","rftt"]',
    output: '"wertf"',
    why: "Adjacent words imply ordering constraints.",
    approach: "Build precedence graph, topological sort. O(total chars).",
  },
  166: {
    statement: "Reconstruct an itinerary using all tickets, lexicographically smallest.",
    input: '[["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]]',
    output: '["JFK","MUC","LHR","SFO","SJC"]',
    why: "Uses every ticket once from JFK.",
    approach: "Hierholzer's Eulerian path with sorted edges. O(E log E).",
  },
  167: {
    statement: "Minimum cost to connect all points (Manhattan distance).",
    input: "[[0,0],[2,2],[3,10],[5,2],[7,0]]",
    output: "20",
    why: "Minimum spanning tree weight is 20.",
    approach: "Prim's MST on the complete graph. O(n² log n).",
  },
  168: {
    statement: "Least time to swim from top-left to bottom-right as water rises.",
    input: "an n×n elevation grid",
    output: "minimum max-elevation along a path",
    why: "Answer is the smallest peak you must cross.",
    approach: "Dijkstra / min-heap minimizing path maximum. O(n² log n).",
  },
  169: {
    statement: "Count provinces (groups of directly/indirectly connected cities).",
    input: "isConnected = [[1,1,0],[1,1,0],[0,0,1]]",
    output: "2",
    why: "Cities 0,1 form one province; city 2 another.",
    approach: "Union-Find or DFS over the matrix. O(n²).",
  },
  170: {
    statement: "Check if a word exists in a grid via adjacent cells.",
    input: 'board grid, word = "ABCCED"',
    output: "true",
    why: "The letters trace a connected path on the board.",
    approach: "DFS backtracking from each cell. O(cells·4^len).",
  },
  // ===== 7. Dynamic Programming =====
  171: {
    statement: "Count distinct ways to climb n stairs taking 1 or 2 steps.",
    input: "n = 3",
    output: "3",
    why: "1+1+1, 1+2, 2+1.",
    approach: "Fibonacci DP. O(n), O(1) space.",
  },
  172: {
    statement: "Min cost to reach the top, paying cost[i] to step off stair i.",
    input: "cost = [10,15,20]",
    output: "15",
    why: "Start at index 1, pay 15, jump to top.",
    approach: "DP: dp[i] = cost[i] + min(prev two). O(n).",
  },
  173: {
    statement: "Max money robbing non-adjacent houses.",
    input: "nums = [2,7,9,3,1]",
    output: "12",
    why: "Rob houses 0,2,4 → 2+9+1 = 12.",
    approach: "DP: dp[i] = max(skip, rob + dp[i-2]). O(n).",
  },
  174: {
    statement: "House Robber where houses form a circle (first & last adjacent).",
    input: "nums = [2,3,2]",
    output: "3",
    why: "Can't rob both ends; best single house is 3.",
    approach: "Run linear robber twice excluding one end. O(n).",
  },
  175: {
    statement: "Count ways to decode a digit string (A=1…Z=26).",
    input: '"226"',
    output: "3",
    why: '"2 2 6", "22 6", "2 26".',
    approach: "DP on valid 1- and 2-digit splits. O(n).",
  },
  176: {
    statement: "Fewest coins to make an amount (∞ supply).",
    input: "coins = [1,2,5], amount = 11",
    output: "3",
    why: "5 + 5 + 1 = 11.",
    approach: "Unbounded-knapsack DP over amounts. O(amount·coins).",
  },
  177: {
    statement: "Contiguous subarray with the largest product.",
    input: "nums = [2,3,-2,4]",
    output: "6",
    why: "[2,3] yields 6.",
    approach: "Track running max and min. O(n).",
  },
  178: {
    statement: "Can s be segmented into dictionary words?",
    input: 's = "leetcode", dict = ["leet","code"]',
    output: "true",
    why: '"leet" + "code" covers the string.',
    approach: "DP over prefixes that are reachable. O(n²).",
  },
  179: {
    statement: "Length of the longest strictly increasing subsequence.",
    input: "nums = [10,9,2,5,3,7,101,18]",
    output: "4",
    why: "[2,3,7,101] has length 4.",
    approach: "Patience sorting with binary search. O(n log n).",
  },
  180: {
    statement: "Can the array be split into two equal-sum subsets?",
    input: "nums = [1,5,11,5]",
    output: "true",
    why: "[1,5,5] and [11] both sum to 11.",
    approach: "Subset-sum DP for total/2. O(n·sum).",
  },
  181: {
    statement: "Count paths from top-left to bottom-right (move right/down).",
    input: "m = 3, n = 7",
    output: "28",
    why: "Number of monotone lattice paths in a 3×7 grid.",
    approach: "Grid DP, or combinatorics. O(mn).",
  },
  182: {
    statement: "Unique paths with obstacles blocking some cells.",
    input: "[[0,0,0],[0,1,0],[0,0,0]]",
    output: "2",
    why: "The center obstacle leaves two routes.",
    approach: "Grid DP, obstacle cells = 0 ways. O(mn).",
  },
  183: {
    statement: "Minimum sum path from top-left to bottom-right.",
    input: "[[1,3,1],[1,5,1],[4,2,1]]",
    output: "7",
    why: "Path 1→3→1→1→1 sums to 7.",
    approach: "Grid DP accumulating minimum. O(mn).",
  },
  184: {
    statement: "Minimum edit distance between two words.",
    input: 'word1 = "horse", word2 = "ros"',
    output: "3",
    why: "Three edits convert horse→ros.",
    approach: "2-D edit-distance DP. O(m·n).",
  },
  185: {
    statement: "Max coins from bursting all balloons (neighbour products).",
    input: "nums = [3,1,5,8]",
    output: "167",
    why: "Optimal burst order yields 167 coins.",
    approach: "Interval DP on last-to-burst. O(n³).",
  },
  186: {
    statement: "Length of the longest common subsequence.",
    input: 'text1 = "abcde", text2 = "ace"',
    output: "3",
    why: '"ace" is common to both.',
    approach: "2-D LCS DP. O(m·n).",
  },
  187: {
    statement: "Count ways to assign +/- so the sum equals target.",
    input: "nums = [1,1,1,1,1], target = 3",
    output: "5",
    why: "Five sign assignments reach 3.",
    approach: "Reduce to subset-sum DP. O(n·sum).",
  },
  188: {
    statement: "Is s3 an interleaving of s1 and s2?",
    input: 's1="aabcc", s2="dbbca", s3="aadbbcbcac"',
    output: "true",
    why: "s3 weaves s1 and s2 preserving order.",
    approach: "2-D DP over consumed prefixes. O(m·n).",
  },
  189: {
    statement: "Maximum alternating (+,−,+…) subsequence sum.",
    input: "nums = [4,2,5,3]",
    output: "7",
    why: "Pick 4 and 5, minus 2: 4−2+5 = 7.",
    approach: "Track best even/odd-length sums. O(n).",
  },
  190: {
    statement: "Count distinct subsequences of s equal to t.",
    input: 's = "rabbbit", t = "rabbit"',
    output: "3",
    why: "Three ways to choose the b's.",
    approach: "2-D DP counting matches. O(m·n).",
  },
  191: {
    statement: "Max stock profit with a 1-day cooldown after selling.",
    input: "prices = [1,2,3,0,2]",
    output: "3",
    why: "Buy 1 sell 3 (profit 2), cooldown, buy 0 sell 2.",
    approach: "State DP: hold/sold/rest. O(n).",
  },
  192: {
    statement: "Max profit with at most k buy-sell transactions.",
    input: "k = 2, prices = [3,2,6,5,0,3]",
    output: "7",
    why: "Buy 2 sell 6 (4) + buy 0 sell 3 (3) = 7.",
    approach: "DP over (transaction, day, holding). O(k·n).",
  },
  // ===== 8. Sorting, Searching & Binary Search =====
  193: {
    statement: "Classic binary search for a target; return index or −1.",
    input: "nums = [-1,0,3,5,9,12], target = 9",
    output: "4",
    why: "9 sits at index 4.",
    approach: "Halve the search range each step. O(log n).",
  },
  194: {
    statement: "Index where target is, or where it would be inserted.",
    input: "nums = [1,3,5,6], target = 5",
    output: "2",
    why: "5 is already at index 2.",
    approach: "Binary search for the lower bound. O(log n).",
  },
  195: {
    statement: "First and last index of a target in a sorted array.",
    input: "nums = [5,7,7,8,8,10], target = 8",
    output: "[3,4]",
    why: "8 spans indices 3 to 4.",
    approach: "Two binary searches (lower/upper bound). O(log n).",
  },
  196: {
    statement: "Search a value in a row- and column-sorted matrix (rows chained).",
    input: "matrix, target = 3",
    output: "true",
    why: "3 exists in the matrix.",
    approach: "Treat as flat sorted array, binary search. O(log mn).",
  },
  197: {
    statement: "Search a matrix sorted left→right and top→bottom.",
    input: "matrix, target = 5",
    output: "true",
    why: "5 is present in the grid.",
    approach: "Start top-right, move left/down. O(m+n).",
  },
  198: {
    statement: "Find minimum in a rotated sorted array that may contain duplicates.",
    input: "nums = [2,2,2,0,1]",
    output: "0",
    why: "The rotation minimum is 0.",
    approach: "Binary search, shrink on equal. O(log n) avg.",
  },
  199: {
    statement: "Min eating speed to finish all bananas within h hours.",
    input: "piles = [3,6,7,11], h = 8",
    output: "4",
    why: "Speed 4 finishes within 8 hours.",
    approach: "Binary search on the answer speed. O(n log max).",
  },
  200: {
    statement: "Min days to make m bouquets of k adjacent bloomed flowers.",
    input: "bloomDay = [1,10,3,10,2], m = 3, k = 1",
    output: "3",
    why: "By day 3, three single-flower bouquets exist.",
    approach: "Binary search on day + greedy check. O(n log max).",
  },
  201: {
    statement: "Split array into m parts minimizing the largest part sum.",
    input: "nums = [7,2,5,10,8], m = 2",
    output: "18",
    why: "[7,2,5] and [10,8]; max sum 18 is minimal.",
    approach: "Binary search on max sum + greedy split. O(n log sum).",
  },
  202: {
    statement: "Median of two sorted arrays.",
    input: "nums1 = [1,3], nums2 = [2]",
    output: "2.0",
    why: "Merged [1,2,3]; median 2.",
    approach: "Binary search partition of the smaller array. O(log min).",
  },
  203: {
    statement: "Find the kth smallest absolute pair distance.",
    input: "nums = [1,3,1], k = 1",
    output: "0",
    why: "Smallest distance |1−1| = 0.",
    approach: "Binary search on distance + count via two pointers. O(n log n).",
  },
  204: {
    statement: "Sort an array (implement a fast sort).",
    input: "nums = [5,2,3,1]",
    output: "[1,2,3,5]",
    why: "Ascending order.",
    approach: "Merge/quick/heap sort. O(n log n).",
  },
  205: {
    statement: "Return the k most frequent elements.",
    input: "nums = [1,1,1,2,2,3], k = 2",
    output: "[1,2]",
    why: "1 (×3) and 2 (×2) are most frequent.",
    approach: "Count + bucket sort by frequency. O(n).",
  },
  206: {
    statement: "Sort characters by decreasing frequency.",
    input: '"tree"',
    output: '"eert"  (or "eetr")',
    why: "e appears twice, so it leads.",
    approach: "Count + bucket by frequency. O(n).",
  },
  207: {
    statement: "Merge all overlapping intervals.",
    input: "[[1,3],[2,6],[8,10],[15,18]]",
    output: "[[1,6],[8,10],[15,18]]",
    why: "[1,3] and [2,6] overlap into [1,6].",
    approach: "Sort by start, merge adjacent. O(n log n).",
  },
  208: {
    statement: "Insert a new interval and merge as needed.",
    input: "intervals = [[1,3],[6,9]], newInterval = [2,5]",
    output: "[[1,5],[6,9]]",
    why: "[2,5] merges with [1,3] into [1,5].",
    approach: "Linear scan: before / overlap / after. O(n).",
  },
  209: {
    statement: "Min intervals to remove so none overlap.",
    input: "[[1,2],[2,3],[3,4],[1,3]]",
    output: "1",
    why: "Removing [1,3] leaves a non-overlapping set.",
    approach: "Greedy by earliest end time. O(n log n).",
  },
  210: {
    statement: "Can a person attend all meetings (no overlaps)?",
    input: "[[0,30],[5,10],[15,20]]",
    output: "false",
    why: "[0,30] overlaps the others.",
    approach: "Sort by start, check adjacent overlaps. O(n log n).",
  },
  211: {
    statement: "Minimum meeting rooms required.",
    input: "[[0,30],[5,10],[15,20]]",
    output: "2",
    why: "[0,30] overlaps another at all times → 2 rooms.",
    approach: "Sort starts/ends, sweep; or min-heap of end times. O(n log n).",
  },
  // ===== 9. Greedy & Bit Manipulation =====
  212: {
    statement: "Can you reach the last index, where nums[i] is the max jump?",
    input: "nums = [2,3,1,1,4]",
    output: "true",
    why: "0→1→4 reaches the end.",
    approach: "Greedy: track the farthest reachable index. O(n).",
  },
  213: {
    statement: "Minimum jumps to reach the last index.",
    input: "nums = [2,3,1,1,4]",
    output: "2",
    why: "Jump 0→1, then 1→4.",
    approach: "Greedy BFS by jump levels. O(n).",
  },
  214: {
    statement: "Find the start gas station to complete the circuit, or −1.",
    input: "gas = [1,2,3,4,5], cost = [3,4,5,1,2]",
    output: "3",
    why: "Starting at station 3 completes the loop.",
    approach: "Greedy: reset start when tank goes negative. O(n).",
  },
  215: {
    statement: "Can the hand be rearranged into groups of groupSize consecutive cards?",
    input: "hand = [1,2,3,6,2,3,4,7,8], groupSize = 3",
    output: "true",
    why: "[1,2,3],[2,3,4],[6,7,8] all consecutive.",
    approach: "Count map + greedily build runs from the min. O(n log n).",
  },
  216: {
    statement: "Min arrows to burst all balloons (overlapping intervals).",
    input: "points = [[10,16],[2,8],[1,6],[7,12]]",
    output: "2",
    why: "Two shots cover all four balloons.",
    approach: "Greedy by earliest end, shoot at it. O(n log n).",
  },
  217: {
    statement: "Every element appears 3× except one; find it.",
    input: "nums = [2,2,3,2]",
    output: "3",
    why: "Only 3 appears once.",
    approach: "Bit counts mod 3, or two-state masks. O(n), O(1).",
  },
  218: {
    statement: "Exactly two elements appear once; find both.",
    input: "nums = [1,2,1,3,2,5]",
    output: "[3,5]",
    why: "3 and 5 are the unpaired values.",
    approach: "XOR all, split by a differing bit. O(n), O(1).",
  },
  219: {
    statement: "Count set bits (Hamming weight) of an integer.",
    input: "n = 11  (1011₂)",
    output: "3",
    why: "1011 has three 1-bits.",
    approach: "Repeatedly clear lowest bit n &= n−1. O(set bits).",
  },
  220: {
    statement: "For 0..n, count the set bits of each number.",
    input: "n = 5",
    output: "[0,1,1,2,1,2]",
    why: "Bit counts of 0,1,2,3,4,5.",
    approach: "DP: bits[i] = bits[i>>1] + (i&1). O(n).",
  },
  221: {
    statement: "Reverse the bits of a 32-bit unsigned integer.",
    input: "n = 43261596  (00000010100101000001111010011100)",
    output: "964176192  (00111001011110000010100101000000)",
    why: "The 32-bit pattern is mirrored.",
    approach: "Shift bits out and into the result. O(32).",
  },
  222: {
    statement: "Find the missing number in 0..n.",
    input: "nums = [3,0,1]",
    output: "2",
    why: "2 is absent from 0..3.",
    approach: "XOR indices with values, or sum formula. O(n).",
  },
  223: {
    statement: "Add two integers without using + or −.",
    input: "a = 2, b = 3",
    output: "5",
    why: "2 + 3 = 5 via bit operations.",
    approach: "XOR = sum, AND<<1 = carry; loop. O(1).",
  },
  224: {
    statement: "Maximum XOR of any two numbers in the array.",
    input: "nums = [3,10,5,25,2,8]",
    output: "28",
    why: "5 XOR 25 = 28 is the maximum.",
    approach: "Bitwise trie, greedily pick opposite bits. O(n·32).",
  },
  225: {
    statement: "Return all subsets of a set of distinct integers.",
    input: "nums = [1,2,3]",
    output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
    why: "All 2³ = 8 subsets.",
    approach: "Backtracking or bitmask enumeration. O(n·2ⁿ).",
  },
  226: {
    statement: "Return all unique subsets when the input may contain duplicates.",
    input: "nums = [1,2,2]",
    output: "[[],[1],[1,2],[1,2,2],[2],[2,2]]",
    why: "Duplicate subsets are excluded.",
    approach: "Sort, backtrack skipping repeated choices. O(n·2ⁿ).",
  },
};
